### ISSUE TITLE
configuration link is broken

### ISSUE THREAD

**Issue by balasivagnanam** [genu/parse-backend#1]
This code is very helpful but I would like to know something on using this.

What is the best practice to use the api key so that it cannot be seen from the browser. or hacked easily.
The configuration link provided in the documentation is broken.

**Comment by genu** [comment]
The Application key and the javascript keys are not expected to be private.

A person can't hack an app using the app and js keys if you implement the proper security rules.

See [Parse Security](https://parse.com/docs/js/guide#security) for more information on how to secure an app.

**Comment by balasivagnanam** [comment]
thanks a lot
