### ISSUE TITLE
injection error

### ISSUE THREAD

**Issue by balasivagnanam** [genu/parse-backend#2]
I am trying to inject the parse backend to my app. but i am getting an error.

```
var app = angular.module('crickifyApp', ['ui.bootstrap', 'ui.router', 'autofields', 'autofields.time', 'module.ParseBackend']);
```

I am using the parse-backend.min.js from the dist and loading it in my index.html

is there any other dependency that I have to load with it?

sorry I am newbie with angular and parse.

![image](https://cloud.githubusercontent.com/assets/4233785/10266433/cc8557c6-6a93-11e5-875f-cd7dacdef86a.png)

**Comment by genu** [comment]
Hi @balasivagnanam 

Is parse-backend.min.js actually loading in your index.html file? (check chrome tools)

**Comment by balasivagnanam** [comment]
1 -> Yes I think it is loading, as I dont see any file not found error in the console.
2 -> It says uncaught error

![image](https://cloud.githubusercontent.com/assets/4233785/10266443/a19927f8-6a94-11e5-858e-7eeb33c0c2f9.png)

and I am getting unexpected string here,

```
app.config(function('ParseBackendProvider'){
    ParseBackendProvider.setApplicationId('ugbLrkTf98vnvNJeOcEY8PEcDNg6F1qkpUy1yBZK');
    ParseBackendProvider.setJavascriptKey('aBDbWZeQJhYW26EdjXN8FE8sluSWE9XuPEKpIeNE');
});
```

I assume it is because of the injection error

**Comment by balasivagnanam** [comment]
hi sorry, i had one other app.config which was causing the error. I think its getting injected now. Will try to do some CRUD.

Thanks for your time.
